---
kind: pipeline
name: build

steps:
- name: build
  image: golang:1.11
  commands:
  - go test

---
kind: pipeline
name: deploy

steps:
- name: build
  image: plugins/docker
  settings:
    repo: hanjunlee/completed-pod-cleaner
    create_repository: true
    auto_tag: true
    username: hanjunlee
    password: 
      from_secret: docker_password

trigger:
  event:
  - tag