---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: completed-pod-cleaner
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: completed-pod-cleaner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: completed-pod-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: completed-pod-cleaner
subjects:
  - kind: ServiceAccount
    name: completed-pod-cleaner
    namespace: default